module.exports = {
	plugins: [
		import('@ianvs/prettier-plugin-sort-imports'),
		import('prettier-plugin-tailwindcss'),
	],
	trailingComma: 'es5',
	tabWidth: 2,
	semi: false,
	singleQuote: true,
	useTabs: true,
	jsxSingleQuote: true,
	importOrder: [
		'react/*',
		'next/*',
		'@/components/*',
		'@/lib/*',
		'@/hooks/*',
		'@/styles/*',
		'@/types/*',
		'^[./]',
	],
	// importOrderBuiltinModulesToTop: true,
	// importOrderCaseInsensitive: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	// importOrderMergeDuplicateImports: true,
	// importOrderCombineTypeAndValueImports: true,
	// importOrderSeparation: false,
	// importOrderSortSpecifiers: true,
}
